# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  android_config: &android_config
    docker:
      # specify the version you desire here
      - image: circleci/android:api-28

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  test:
    <<: *android_config

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle

      - run:
          name: Run Lint
          command: ./gradlew lint test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results

  fast_test:
    <<: *android_config

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle

      - restore_cache:
          key: version-codes

      - run:
          name: Up version code
          command: ./gradlew upVersionCode

      - save_cache:
          key: version-codes
          paths:
            - version_codes.properties

  build:
    <<: *android_config

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - restore_cache:
          key: version-codes

      #- run:
      #    name: Build
      #    command: ./gradlew assembleDebug

      - run:
          name: Up version code
          command: ./gradlew upVersionCode

      - save_cache:
          paths:
            - version_codes.properties
          key: version-codes

      #- store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #    path: app/build/outputs/apk/debug
      #    destination: apk

workflows:
  version: 2
  workflow:
    jobs:
#      - test
      - build:
#          requires:
#            - test
          filters:
            branches:
              only:
                - /version-.*/